export type Market = 'rd' | 'usa' | 'both'

export interface Feature {
  icon: string
  titleEs: string
  titleEn: string
  descEs: string
  descEn: string
  highlight?: boolean
  badge?: string
}

export interface Product {
  slug: string
  name: string
  nameAccent?: string
  market: Market
  color: string
  icon: string
  descEs: string
  descEn: string
  cardDescEs: string
  cardDescEn: string
  tags: { es: string; en: string }[]
  features: Feature[]
  ctaEs: string
  ctaEn: string
  ctaSubEs: string
  ctaSubEn: string
  metaTitleEs: string
  metaTitleEn: string
  metaDescEs: string
  metaDescEn: string
}

export const products: Product[] = [
  {
    slug: 'pventa',
    name: 'PVenta',
    nameAccent: 'ERP',
    market: 'both',
    color: 'cyan',
    icon: 'FileBarChart',
    descEs: 'Sistema ERP de gestion empresarial con cotizaciones, ventas y facturacion electronica DGII (e-CF). Ciclo completo desde la cotizacion hasta la facturacion con pagos integrados por Stripe, Azul y Carnet. Disponible tambien como app movil para Android e iOS.',
    descEn: 'Enterprise Resource Planning (ERP) system with quotations, sales and DGII electronic invoicing (e-CF). Complete cycle from quotation to invoicing with integrated payments via Stripe, Azul and Carnet. Also available as a mobile app for Android and iOS.',
    cardDescEs: 'Sistema ERP de gestion empresarial. Cotizaciones, ventas y facturacion electronica DGII. Ciclo completo con pagos integrados. App movil disponible.',
    cardDescEn: 'Enterprise Resource Planning (ERP) system. Quotations, sales and DGII e-invoicing. Complete cycle with integrated payments. Mobile app available.',
    tags: [],
    ctaEs: 'Potencia tu negocio con PVenta ERP',
    ctaEn: 'Power your business with PVenta ERP',
    ctaSubEs: 'Del presupuesto al cobro en una sola plataforma. Solicita una demostracion hoy.',
    ctaSubEn: 'From budget to collection in a single platform. Request a demo today.',
    metaTitleEs: 'PVenta ERP - XoulTec | Sistema ERP de Cotizaciones y Ventas',
    metaTitleEn: 'PVenta ERP - XoulTec | ERP Quotation & Sales System',
    metaDescEs: 'PVenta ERP: Sistema ERP de gestion de cotizaciones, ventas y facturacion electronica con pagos integrados para RD y USA. App movil disponible.',
    metaDescEn: 'PVenta ERP: Enterprise quotation, sales and electronic invoicing system with integrated payments for DR and USA. Mobile app available.',
    features: [
      { icon: 'FileText', titleEs: 'Cotizaciones', titleEn: 'Quotations', descEs: 'Crea y gestiona cotizaciones con seguimiento de estado. Conversion automatica a ordenes de venta.', descEn: 'Create and manage quotations with status tracking. Automatic conversion to sales orders.' },
      { icon: 'ShoppingBag', titleEs: 'Ordenes de Venta', titleEn: 'Sales Orders', descEs: 'Gestion completa del ciclo de venta. Desde la creacion hasta el despacho y facturacion final.', descEn: 'Complete sales cycle management. From creation to dispatch and final invoicing.' },
      { icon: 'CreditCard', titleEs: 'Pagos Integrados', titleEn: 'Integrated Payments', descEs: 'Stripe para USA, Azul y Carnet para RD. Procesamiento de pagos seguro directamente en el sistema.', descEn: 'Stripe for USA, Azul and Carnet for DR. Secure payment processing directly in the system.' },
      { icon: 'Package', titleEs: 'Catalogo de Productos', titleEn: 'Product Catalog', descEs: 'Catalogo organizado por grupos y zonas. Precios, descuentos multi-nivel y condiciones de pago configurables.', descEn: 'Catalog organized by groups and zones. Prices, multi-level discounts and configurable payment terms.' },
      { icon: 'FileDown', titleEs: 'Documentos y Reportes', titleEn: 'Documents & Reports', descEs: 'Generacion automatica de PDF y Excel. Cotizaciones, facturas y reportes de ventas profesionales.', descEn: 'Automatic PDF and Excel generation. Professional quotations, invoices and sales reports.' },
      { icon: 'ShieldCheck', titleEs: 'Autorizaciones', titleEn: 'Authorizations', descEs: 'Sistema avanzado de autorizaciones a nivel de formulario y control. Permisos granulares por perfil de usuario.', descEn: 'Advanced authorization system at form and control level. Granular permissions by user profile.' },
      { icon: 'HandCoins', titleEs: 'Cuentas por Cobrar', titleEn: 'Accounts Receivable', descEs: 'Control de facturas pendientes, estados de cuenta, cobros parciales y totales. Seguimiento de vencimientos y antiguedad de saldos.', descEn: 'Outstanding invoice tracking, account statements, partial and full collections. Due date monitoring and aging balances.' },
      { icon: 'Warehouse', titleEs: 'Inventario', titleEn: 'Inventory', descEs: 'Control completo de inventario con entradas, salidas, transferencias y ajustes. Seguimiento de existencias en tiempo real por almacen.', descEn: 'Complete inventory control with receipts, dispatches, transfers and adjustments. Real-time stock tracking by warehouse.' },
      { icon: 'Receipt', titleEs: 'Cuentas por Pagar', titleEn: 'Accounts Payable', descEs: 'Gestion de facturas de suplidores, programacion de pagos, notas de credito y control de vencimientos. Flujo de caja optimizado.', descEn: 'Supplier invoice management, payment scheduling, credit notes and due date control. Optimized cash flow.' },
      { icon: 'BookOpen', titleEs: 'Contabilidad General', titleEn: 'General Ledger', descEs: 'Plan de cuentas configurable, asientos contables, balance general y estado de resultados. Integracion automatica con todos los modulos.', descEn: 'Configurable chart of accounts, journal entries, balance sheet and income statement. Automatic integration with all modules.' },
      { icon: 'Landmark', titleEs: 'Conciliacion Bancaria', titleEn: 'Bank Reconciliation', descEs: 'Conciliacion de cuentas bancarias, registro de cheques, depositos y transferencias. Control total de tesoreria integrado con contabilidad.', descEn: 'Bank account reconciliation, check register, deposits and transfers. Full treasury control integrated with accounting.' },
      { icon: 'Smartphone', titleEs: 'App Movil', titleEn: 'Mobile App', descEs: 'Accede a PVenta desde tu celular. Gestiona cotizaciones, ventas y clientes en movimiento.', descEn: 'Access PVenta from your phone. Manage quotations, sales and customers on the go.', highlight: true, badge: 'Android & iOS' },
      { icon: 'FileCheck', titleEs: 'e-CF DGII', titleEn: 'e-CF DGII', descEs: 'Cumplimiento total con los requisitos de la DGII para facturacion electronica (e-CF). Generacion de comprobantes fiscales electronicos, NCF, envio automatico y reportes 606/607.', descEn: 'Full compliance with DGII electronic invoicing requirements (e-CF). Electronic fiscal receipt generation, NCF, automatic submission and 606/607 reports.', highlight: true, badge: 'Certificado' },
    ],
  },
  {
    slug: 'easypos',
    name: 'EasyPOS',
    market: 'both',
    color: 'rose',
    icon: 'Utensils',
    descEs: 'El POS mas completo para restaurantes. Ordenes en tiempo real, pantalla de cocina (KDS), gestion de mesas, delivery, inventario, personal y propinas en una sola plataforma.',
    descEn: 'The most complete restaurant POS. Real-time orders, kitchen display (KDS), table management, delivery, inventory, staff and tips on a single platform.',
    cardDescEs: 'POS completo para restaurantes. Ordenes en tiempo real, cocina (KDS), mesas, delivery, inventario y propinas.',
    cardDescEn: 'Complete restaurant POS. Real-time orders, kitchen display (KDS), tables, delivery, inventory and tips.',
    tags: [
      { es: 'POS', en: 'POS' },
      { es: 'KDS', en: 'KDS' },
      { es: 'Tiempo Real', en: 'Real-time' },
    ],
    ctaEs: 'Lleva tu restaurante al siguiente nivel',
    ctaEn: 'Take your restaurant to the next level',
    ctaSubEs: 'EasyPOS tiene todo lo que tu restaurante necesita. Solicita una demostracion hoy.',
    ctaSubEn: 'EasyPOS has everything your restaurant needs. Request a demo today.',
    metaTitleEs: 'EasyPOS - XoulTec | POS para Restaurantes',
    metaTitleEn: 'EasyPOS - XoulTec | Restaurant Point of Sale',
    metaDescEs: 'EasyPOS: POS completo para restaurantes con pantalla de cocina en tiempo real, gestion de mesas, delivery e inventario.',
    metaDescEn: 'EasyPOS: Complete restaurant POS with real-time kitchen display, table management, online ordering, inventory and staff management.',
    features: [
      { icon: 'Monitor', titleEs: 'Terminal POS', titleEn: 'POS Terminal', descEs: 'Interfaz de punto de venta intuitiva con menu visual. Ordenes rapidas, modificadores, notas y split de cuentas.', descEn: 'Intuitive point of sale interface with visual menu. Quick orders, modifiers, notes and check splitting.' },
      { icon: 'ChefHat', titleEs: 'Pantalla de Cocina', titleEn: 'Kitchen Display (KDS)', descEs: 'Sistema de display de cocina en tiempo real via WebSocket. Los pedidos llegan al instante con prioridad y temporizadores.', descEn: 'Real-time kitchen display system via WebSocket. Orders arrive instantly with priority and timers.' },
      { icon: 'LayoutGrid', titleEs: 'Gestion de Mesas', titleEn: 'Table Management', descEs: 'Plano de piso interactivo con asignacion de meseros. Estado de mesas en tiempo real y reservaciones.', descEn: 'Interactive floor plan with server assignment. Real-time table status and reservations.' },
      { icon: 'Truck', titleEs: 'Ordenes Online y Delivery', titleEn: 'Online Orders & Delivery', descEs: 'Plataforma de ordenes online integrada. Recibe pedidos de delivery directamente en el sistema POS.', descEn: 'Integrated online ordering platform. Receive delivery orders directly in the POS system.' },
      { icon: 'CreditCard', titleEs: 'Pagos Multiples', titleEn: 'Multiple Payments', descEs: 'Stripe, efectivo, tarjeta, transferencia. Division de cuentas, bar tabs y pantalla de cliente integrada.', descEn: 'Stripe, cash, card, transfer. Check splitting, bar tabs and integrated customer display.' },
      { icon: 'Clock', titleEs: 'Personal y Propinas', titleEn: 'Staff & Tips', descEs: 'Control de entrada/salida, tarjetas de tiempo, gestion de propinas y reportes laborales detallados.', descEn: 'Clock-in/out, timecards, tip management and detailed labor reports.' },
      { icon: 'Warehouse', titleEs: 'Inventario', titleEn: 'Inventory', descEs: 'Control de inventario con auto-86 (agotamiento automatico), proveedores, ordenes de compra y costeo de recetas.', descEn: 'Inventory control with auto-86 (automatic unavailability), suppliers, purchase orders and recipe costing.' },
      { icon: 'Heart', titleEs: 'Lealtad y Gift Cards', titleEn: 'Loyalty & Gift Cards', descEs: 'Programa de lealtad integrado y gestion de tarjetas de regalo para fidelizar a tus clientes.', descEn: 'Integrated loyalty program and gift card management to retain your customers.' },
      { icon: 'Zap', titleEs: 'Tiempo Real', titleEn: 'Real-time', descEs: 'Comunicacion WebSocket en tiempo real entre POS, cocina y mesas. Todo sincronizado al instante.', descEn: 'Real-time WebSocket communication between POS, kitchen and tables. Everything synced instantly.' },
    ],
  },
  {
    slug: 'eclinic',
    name: 'eClinic',
    market: 'both',
    color: 'blue',
    icon: 'HeartPulse',
    descEs: 'Sistema integral de gestion clinica y medica con cumplimiento HIPAA. Administra pacientes, citas, diagnosticos, seguros y autorizaciones en una plataforma moderna y segura.',
    descEn: 'HIPAA-compliant clinical and medical management system. Manage patients, appointments, diagnostics, insurance and authorizations on a modern, secure platform.',
    cardDescEs: 'Sistema integral de gestion clinica y medica con cumplimiento HIPAA. Manejo de pacientes, citas, diagnosticos, seguros y autorizaciones.',
    cardDescEn: 'HIPAA-compliant clinical management system. Patient management, appointments, diagnostics, insurance and authorizations.',
    tags: [
      { es: 'Pacientes', en: 'Patients' },
      { es: 'Diagnosticos', en: 'Diagnostics' },
      { es: 'Seguros', en: 'Insurance' },
    ],
    ctaEs: 'Moderniza tu clinica con eClinic',
    ctaEn: 'Modernize your clinic with eClinic',
    ctaSubEs: 'Solicita una demostracion personalizada y descubre como eClinic puede transformar la gestion de tu clinica.',
    ctaSubEn: 'Request a personalized demo and discover how eClinic can transform your clinic management.',
    metaTitleEs: 'eClinic - XoulTec | Sistema de Gestion Clinica',
    metaTitleEn: 'eClinic - XoulTec | Clinical Management System',
    metaDescEs: 'eClinic: Sistema integral de gestion clinica y medica. Pacientes, citas, diagnosticos, seguros y autorizaciones.',
    metaDescEn: 'eClinic: Comprehensive clinical and medical management system. Patients, appointments, diagnostics, insurance and authorizations.',
    features: [
      { icon: 'Users', titleEs: 'Gestion de Pacientes', titleEn: 'Patient Management', descEs: 'Registro completo de pacientes con historial de visitas, diagnosticos y tratamientos. Busqueda rapida y filtros avanzados.', descEn: 'Complete patient records with visit history, diagnostics and treatments. Fast search and advanced filters.' },
      { icon: 'Stethoscope', titleEs: 'Diagnosticos y Visitas', titleEn: 'Diagnostics & Visits', descEs: 'Seguimiento detallado de cada visita medica con diagnosticos, notas clinicas y planes de tratamiento.', descEn: 'Detailed tracking of each medical visit with diagnostics, clinical notes and treatment plans.' },
      { icon: 'ShieldCheck', titleEs: 'Seguros y Autorizaciones', titleEn: 'Insurance & Authorizations', descEs: 'Gestion de aseguradoras, planes de cobertura y sistema de autorizaciones multi-formulario.', descEn: 'Insurance provider management, coverage plans and multi-form authorization system.' },
      { icon: 'Lock', titleEs: 'Control de Acceso', titleEn: 'Access Control', descEs: 'Perfiles de usuario con permisos granulares por formulario y funcion. Seguridad de datos medicos garantizada.', descEn: 'User profiles with granular permissions by form and function. Medical data security guaranteed.' },
      { icon: 'ShieldCheck', titleEs: 'HIPAA Compliant', titleEn: 'HIPAA Compliant', descEs: 'Cumplimiento total con las regulaciones HIPAA. Proteccion de datos de salud protegidos (PHI), encriptacion, auditorias de acceso y politicas de privacidad integradas.', descEn: 'Full HIPAA compliance. Protected Health Information (PHI) safeguards, encryption, access audits and built-in privacy policies.', highlight: true, badge: 'Certified' },
      { icon: 'Monitor', titleEs: 'Interfaz Moderna', titleEn: 'Modern Interface', descEs: 'Interfaz web moderna y responsiva. Accede desde cualquier dispositivo con navegador web.', descEn: 'Modern, responsive web interface. Access from any device with a web browser.' },
    ],
  },
  {
    slug: 'autoshop',
    name: 'AutoShop Pro',
    market: 'both',
    color: 'orange',
    icon: 'Wrench',
    descEs: 'Sistema completo para talleres mecanicos y tiendas de repuestos de vehiculos. Cotizaciones, ordenes de trabajo, inventario de partes, facturacion y pagos integrados con Stripe Connect.',
    descEn: 'Complete system for auto repair shops and vehicle parts stores. Quotes, work orders, parts inventory, invoicing and integrated payments with Stripe Connect.',
    cardDescEs: 'Sistema para talleres y tiendas de repuestos. Cotizaciones, ordenes de trabajo, inventario de partes, facturacion y pagos con Stripe.',
    cardDescEn: 'Auto repair shop and parts store system. Quotes, work orders, parts inventory, invoicing and Stripe payments.',
    tags: [
      { es: 'Ordenes de Trabajo', en: 'Work Orders' },
      { es: 'Repuestos', en: 'Parts' },
      { es: 'Stripe', en: 'Stripe' },
    ],
    ctaEs: 'Lleva tu taller al siguiente nivel',
    ctaEn: 'Take your shop to the next level',
    ctaSubEs: 'AutoShop Pro tiene todo lo que tu taller o tienda de repuestos necesita. Solicita una demostracion hoy.',
    ctaSubEn: 'AutoShop Pro has everything your repair shop or parts store needs. Request a demo today.',
    metaTitleEs: 'AutoShop Pro - XoulTec | Sistema para Talleres y Repuestos',
    metaTitleEn: 'AutoShop Pro - XoulTec | Auto Repair Shop System',
    metaDescEs: 'AutoShop Pro: Sistema para talleres mecanicos y tiendas de repuestos. Ordenes de trabajo, inventario de partes, facturacion y pagos con Stripe.',
    metaDescEn: 'AutoShop Pro: Auto repair shop and parts store system. Work orders, parts inventory, invoicing and Stripe payments.',
    features: [
      { icon: 'Car', titleEs: 'Clientes y Vehiculos', titleEn: 'Customers & Vehicles', descEs: 'Registro de clientes con sus vehiculos: marca, modelo, ano, VIN, placa, millaje y especificaciones de motor. Historial completo por vehiculo.', descEn: 'Customer records with their vehicles: make, model, year, VIN, license plate, mileage and engine specs. Complete history per vehicle.' },
      { icon: 'FileText', titleEs: 'Cotizaciones', titleEn: 'Quotes', descEs: 'Crea cotizaciones detalladas con servicios y repuestos. Periodo de vigencia configurable y conversion automatica a orden de trabajo.', descEn: 'Create detailed quotes with services and parts. Configurable validity period and automatic conversion to work orders.' },
      { icon: 'ClipboardList', titleEs: 'Ordenes de Trabajo', titleEn: 'Work Orders', descEs: 'Seguimiento de ordenes con estados (abierta, en progreso, completada). Asignacion de tecnicos, horas de labor y control de millaje.', descEn: 'Order tracking with statuses (open, in progress, completed). Technician assignment, labor hours and mileage tracking.' },
      { icon: 'Package', titleEs: 'Inventario de Repuestos', titleEn: 'Parts Inventory', descEs: 'Catalogo de partes con costo, precio de venta, stock, alertas de minimo, categorias, marcas y numeros de parte.', descEn: 'Parts catalog with cost, selling price, stock levels, low-stock alerts, categories, brands and part numbers.' },
      { icon: 'Receipt', titleEs: 'Facturacion', titleEn: 'Invoicing', descEs: 'Genera facturas desde ordenes de trabajo con lineas detalladas de servicios, partes y otros cargos. Descuentos e impuestos configurables.', descEn: 'Generate invoices from work orders with detailed service, parts and other charge lines. Configurable discounts and taxes.' },
      { icon: 'CreditCard', titleEs: 'Pagos con Stripe Connect', titleEn: 'Stripe Connect Payments', descEs: 'Pagos integrados con Stripe Connect. Efectivo, cheque, tarjeta, transferencia. Cada taller como cuenta conectada con comisiones automaticas.', descEn: 'Integrated Stripe Connect payments. Cash, check, card, transfer. Each shop as a connected account with automatic fees.' },
      { icon: 'Settings', titleEs: 'Catalogo de Servicios', titleEn: 'Service Catalog', descEs: 'Servicios predefinidos con precios estandar y horas de labor estimadas. Organizados por categoria para cotizaciones rapidas.', descEn: 'Predefined services with standard pricing and estimated labor hours. Organized by category for quick quoting.' },
      { icon: 'BarChart3', titleEs: 'Dashboard y Reportes', titleEn: 'Dashboard & Reports', descEs: 'Panel en tiempo real con ingresos del dia, ordenes pendientes, items bajo stock y facturas vencidas. Reportes de caja diaria e ingresos.', descEn: 'Real-time dashboard with today\'s revenue, pending orders, low-stock items and overdue invoices. Daily cash and revenue reports.' },
      { icon: 'Building2', titleEs: 'Multi-tenant SaaS', titleEn: 'Multi-tenant SaaS', descEs: 'Plataforma SaaS multi-taller. Cada taller con su base de datos aislada, usuarios y configuracion independiente.', descEn: 'Multi-shop SaaS platform. Each shop with its own isolated database, users and independent configuration.' },
    ],
  },
  {
    slug: 'nomina',
    name: 'Nomina',
    market: 'both',
    color: 'amber',
    icon: 'Banknote',
    descEs: 'Sistema de nomina multi-pais con motor de calculo fiscal inteligente. Procesa nominas para Republica Dominicana y Estados Unidos con las regulaciones de cada pais.',
    descEn: 'Multi-country payroll system with intelligent tax calculation engine. Process payroll for the Dominican Republic and the United States with each country\'s regulations.',
    cardDescEs: 'Sistema de nomina multi-pais. Calculo automatico de impuestos, deducciones, liquidaciones y reportes fiscales para RD y USA.',
    cardDescEn: 'Multi-country payroll system. Automatic tax calculations, deductions, severance and fiscal reports for DR and USA.',
    tags: [
      { es: 'Impuestos', en: 'Taxes' },
      { es: 'Multi-pais', en: 'Multi-country' },
      { es: 'Deducciones', en: 'Deductions' },
    ],
    ctaEs: 'Simplifica tu nomina',
    ctaEn: 'Simplify your payroll',
    ctaSubEs: 'Un solo sistema para manejar la nomina en RD y USA. Solicita una demostracion hoy.',
    ctaSubEn: 'One system to manage payroll in DR and USA. Request a demo today.',
    metaTitleEs: 'Nomina - XoulTec | Sistema de Nomina Multi-pais',
    metaTitleEn: 'Payroll - XoulTec | Multi-Country Payroll System',
    metaDescEs: 'Nomina: Sistema de nomina multi-pais para RD y USA. Calculo automatico de impuestos, deducciones y liquidaciones.',
    metaDescEn: 'Payroll: Multi-country payroll system for DR and USA. Automatic tax calculations, deductions and severance.',
    features: [
      { icon: 'Globe', titleEs: 'Multi-Pais', titleEn: 'Multi-Country', descEs: 'Motor de calculo fiscal basado en datos, no en codigo. Agrega nuevos paises sin cambiar el sistema.', descEn: 'Data-driven tax calculation engine. Add new countries without changing the system.' },
      { icon: 'Calculator', titleEs: 'Calculo de Impuestos', titleEn: 'Tax Calculations', descEs: 'Componentes fiscales, escalas y tramos configurables por pais. ISR, TSS, ITBIS para RD; Federal, State, FICA para USA.', descEn: 'Configurable tax components, scales and brackets by country. ISR, TSS for DR; Federal, State, FICA for USA.' },
      { icon: 'UserMinus', titleEs: 'Liquidaciones', titleEn: 'Severance', descEs: 'Reglas de liquidacion y prestaciones laborales configurables. Calculo automatico segun tiempo de servicio y pais.', descEn: 'Configurable severance and labor benefit rules. Automatic calculation based on service time and country.' },
      { icon: 'Users', titleEs: 'Gestion de Empleados', titleEn: 'Employee Management', descEs: 'Registro completo de empleados con departamentos, posiciones, historial salarial y documentos.', descEn: 'Complete employee records with departments, positions, salary history and documents.' },
      { icon: 'FileMinus', titleEs: 'Deducciones Flexibles', titleEn: 'Flexible Deductions', descEs: 'Sistema de deducciones configurable: prestamos, seguros, aportes voluntarios y mas. Calculo automatico en cada nomina.', descEn: 'Configurable deduction system: loans, insurance, voluntary contributions and more. Automatic calculation in each payroll.' },
      { icon: 'Banknote', titleEs: 'Multi-Moneda', titleEn: 'Multi-Currency', descEs: 'Soporte completo para Peso Dominicano (DOP) y Dolar Estadounidense (USD). Formato regional automatico.', descEn: 'Full support for Dominican Peso (DOP) and US Dollar (USD). Automatic regional formatting.' },
    ],
  },
  {
    slug: 'eduapp',
    name: 'EduApp',
    market: 'rd',
    color: 'emerald',
    icon: 'GraduationCap',
    descEs: 'Sistema de gestion escolar completo. Administra estudiantes, calificaciones, cobros, punto de venta escolar y boletines academicos desde una sola plataforma.',
    descEn: 'Complete school management system. Manage students, grades, billing, school POS and academic report cards from a single platform.',
    cardDescEs: 'Sistema de gestion escolar completo. Estudiantes, calificaciones, cobros, punto de venta y boletines academicos.',
    cardDescEn: 'Complete school management system. Students, grades, billing, point of sale and academic report cards.',
    tags: [
      { es: 'Estudiantes', en: 'Students' },
      { es: 'Calificaciones', en: 'Grades' },
      { es: 'Cobros', en: 'Billing' },
    ],
    ctaEs: 'Digitaliza tu colegio con EduApp',
    ctaEn: 'Digitize your school with EduApp',
    ctaSubEs: 'Solicita una demostracion y descubre como EduApp simplifica la gestion de tu institucion educativa.',
    ctaSubEn: "Request a demo and discover how EduApp simplifies your educational institution's management.",
    metaTitleEs: 'EduApp - XoulTec | Sistema de Gestion Escolar',
    metaTitleEn: 'EduApp - XoulTec | School Management System',
    metaDescEs: 'EduApp: Sistema de gestion escolar completo. Estudiantes, calificaciones, cobros, punto de venta y boletines academicos.',
    metaDescEn: 'EduApp: Complete school management system. Students, grades, billing, point of sale and academic report cards.',
    features: [
      { icon: 'UserCheck', titleEs: 'Gestion de Estudiantes', titleEn: 'Student Management', descEs: 'Inscripcion, seguimiento academico, contactos de emergencia y relacion con padres/tutores en un solo lugar.', descEn: 'Enrollment, academic tracking, emergency contacts and parent/guardian relationships in one place.' },
      { icon: 'BookOpen', titleEs: 'Gestion Academica', titleEn: 'Academic Management', descEs: 'Asignacion de profesores, materias, calificaciones parciales y generacion automatica de boletines.', descEn: 'Teacher assignments, subjects, partial grades and automatic report card generation.' },
      { icon: 'Wallet', titleEs: 'Cobros y Finanzas', titleEn: 'Billing & Finance', descEs: 'Conceptos de pago, becas, seguimiento de cobros, reportes de morosidad y caja diaria.', descEn: 'Fee concepts, scholarships, payment tracking, delinquency reports and daily cash.' },
      { icon: 'ShoppingCart', titleEs: 'Punto de Venta', titleEn: 'Point of Sale', descEs: 'POS integrado para libreria y cafeteria escolar con control de inventario y reportes de ventas.', descEn: 'Integrated POS for school bookstore and cafeteria with inventory control and sales reports.' },
      { icon: 'Layers', titleEs: 'Estructura Academica', titleEn: 'Academic Structure', descEs: 'Grados, secciones, grupos, anos escolares y periodos configurables para cada institucion.', descEn: 'Grades, sections, groups, school years and configurable periods for each institution.' },
      { icon: 'Building2', titleEs: 'Multi-tenant', titleEn: 'Multi-tenant', descEs: 'Arquitectura SaaS multi-colegio. Cada institucion con su base de datos aislada y segura.', descEn: 'Multi-school SaaS architecture. Each institution with its own isolated and secure database.' },
    ],
  },
  {
    slug: 'fri',
    name: 'FRI',
    market: 'rd',
    color: 'purple',
    icon: 'Church',
    descEs: 'Sistema especializado en gestion de ingresos para iglesias y organizaciones religiosas. Control total de recibos, cuentas contables, iglesias y obreros.',
    descEn: 'Specialized income management system for churches and religious organizations. Full control of receipts, GL accounts, churches and staff.',
    cardDescEs: 'Gestion de ingresos para iglesias y organizaciones religiosas. Recibos, cuentas contables, iglesias y obreros.',
    cardDescEn: 'Income management for churches and religious organizations. Receipts, GL accounts, churches and staff.',
    tags: [
      { es: 'Recibos', en: 'Receipts' },
      { es: 'Contabilidad', en: 'Accounting' },
      { es: 'Iglesias', en: 'Churches' },
    ],
    ctaEs: 'Organiza los ingresos de tu iglesia con FRI',
    ctaEn: 'Organize your church income with FRI',
    ctaSubEs: 'Solicita una demostracion y descubre como FRI puede simplificar la contabilidad de tu organizacion religiosa.',
    ctaSubEn: "Request a demo and discover how FRI can simplify your religious organization's accounting.",
    metaTitleEs: 'FRI - XoulTec | Gestion de Ingresos para Iglesias',
    metaTitleEn: 'FRI - XoulTec | Church Income Management',
    metaDescEs: 'FRI: Sistema de gestion de ingresos para iglesias y organizaciones religiosas. Recibos, contabilidad y administracion.',
    metaDescEn: 'FRI: Income management system for churches and religious organizations. Receipts, accounting and administration.',
    features: [
      { icon: 'Receipt', titleEs: 'Gestion de Recibos', titleEn: 'Receipt Management', descEs: 'Recibos de ingreso detallados con lineas por cuenta contable. Numeracion automatica y secuencial.', descEn: 'Detailed income receipts with line items by GL account. Automatic sequential numbering.' },
      { icon: 'BookMarked', titleEs: 'Cuentas Contables', titleEn: 'GL Accounts', descEs: 'Plan de cuentas contables con banderas de retencion. Clasificacion y seguimiento de cada tipo de ingreso.', descEn: 'Chart of GL accounts with retention flags. Classification and tracking of each income type.' },
      { icon: 'Church', titleEs: 'Gestion de Iglesias', titleEn: 'Church Management', descEs: 'Administra multiples iglesias dentro de la organizacion. Estructura jerarquica con presbiterios.', descEn: 'Manage multiple churches within the organization. Hierarchical structure with presbyteries.' },
      { icon: 'Users', titleEs: 'Gestion de Obreros', titleEn: 'Staff Management', descEs: 'Registro completo de obreros con mas de 25 campos de seguimiento. Asignacion a iglesias y roles.', descEn: 'Complete staff records with 25+ tracked fields. Assignment to churches and roles.' },
      { icon: 'GitBranch', titleEs: 'Presbiterios', titleEn: 'Presbyteries', descEs: 'Estructura organizacional con presbiterios. Liderazgo y supervision de grupos de iglesias.', descEn: 'Organizational structure with presbyteries. Leadership and oversight of church groups.' },
      { icon: 'BarChart3', titleEs: 'Reportes', titleEn: 'Reports', descEs: 'Reportes de ingresos por periodo, iglesia, cuenta contable y obrero. Exportacion y analisis financiero.', descEn: 'Income reports by period, church, GL account and staff. Export and financial analysis.' },
    ],
  },
  {
    slug: 'eloan',
    name: 'eLoan',
    market: 'rd',
    color: 'teal',
    icon: 'CircleDollarSign',
    descEs: 'Sistema integral de gestion de prestamos y cobranzas. Administra clientes, cartera de prestamos, cobros, comisiones de cobradores e integracion contable en tiempo real.',
    descEn: 'Comprehensive loan management and collections system. Manage customers, loan portfolios, payments, collector commissions and real-time accounting integration. Modern migration of the legacy SisWinZeo system.',
    cardDescEs: 'Gestion de prestamos y cobranzas. Clientes, cartera de prestamos, cobros, comisiones de cobradores e integracion contable en tiempo real.',
    cardDescEn: 'Loan management and collections. Customers, loan portfolios, payments, collector commissions and real-time accounting integration.',
    tags: [
      { es: 'Prestamos', en: 'Loans' },
      { es: 'Cobranzas', en: 'Collections' },
      { es: 'Contabilidad', en: 'Accounting' },
    ],
    ctaEs: 'Moderniza tu cartera de prestamos con eLoan',
    ctaEn: 'Modernize your loan portfolio with eLoan',
    ctaSubEs: 'Solicita una demostracion y descubre como eLoan puede optimizar la gestion de tu cartera de prestamos.',
    ctaSubEn: 'Request a demo and discover how eLoan can optimize your loan portfolio management.',
    metaTitleEs: 'eLoan - XoulTec | Sistema de Gestion de Prestamos',
    metaTitleEn: 'eLoan - XoulTec | Loan Management System',
    metaDescEs: 'eLoan: Sistema de gestion de prestamos y cobranzas. Cartera de prestamos, cobros, comisiones y contabilidad integrada.',
    metaDescEn: 'eLoan: Loan management and collections system. Loan portfolios, payments, commissions and integrated accounting.',
    features: [
      { icon: 'Users', titleEs: 'Gestion de Clientes', titleEn: 'Customer Management', descEs: 'Registro completo de clientes con informacion de contacto, clasificacion y historial de prestamos. Busqueda rapida y filtros avanzados.', descEn: 'Complete customer records with contact information, classification and loan history. Fast search and advanced filters.' },
      { icon: 'FileText', titleEs: 'Originacion de Prestamos', titleEn: 'Loan Origination', descEs: 'Creacion de prestamos con interes fijo o deslizante. Capitalizacion mensual, quincenal o semanal. Numeracion automatica y secuencial.', descEn: 'Loan creation with fixed or sliding interest. Monthly, biweekly or weekly capitalization. Automatic sequential numbering.' },
      { icon: 'Wallet', titleEs: 'Procesamiento de Pagos', titleEn: 'Payment Processing', descEs: 'Registro de pagos con generacion automatica de recibos en PDF. Integracion contable en tiempo real con asientos automaticos.', descEn: 'Payment recording with automatic PDF receipt generation. Real-time accounting integration with automatic journal entries.' },
      { icon: 'UserCheck', titleEs: 'Gestion de Cobradores', titleEn: 'Collector Management', descEs: 'Administracion de cobradores con seguimiento de comisiones. Reportes de rendimiento y asignacion de cartera por cobrador.', descEn: 'Collector administration with commission tracking. Performance reports and portfolio assignment per collector.' },
      { icon: 'AlertTriangle', titleEs: 'Analisis de Vencimientos', titleEn: 'Aging Analysis', descEs: 'Clasificacion automatica de prestamos vencidos en rangos: 0-30, 31-60, 61-90, 91-120 y 121+ dias. Control de morosidad en tiempo real.', descEn: 'Automatic classification of overdue loans into buckets: 0-30, 31-60, 61-90, 91-120 and 121+ days. Real-time delinquency tracking.' },
      { icon: 'BookOpen', titleEs: 'Integracion Contable', titleEn: 'Accounting Integration', descEs: 'Asientos contables automaticos al procesar pagos. Integracion directa con el sistema de contabilidad general para conciliacion financiera.', descEn: 'Automatic journal entries when processing payments. Direct integration with the general ledger for financial reconciliation.' },
      { icon: 'Landmark', titleEs: 'Catalogo de Instituciones', titleEn: 'Institution Catalog', descEs: 'Gestion de instituciones financieras asociadas. Catalogo centralizado para referencia y operaciones de prestamo.', descEn: 'Management of associated financial institutions. Centralized catalog for loan reference and operations.' },
      { icon: 'BarChart3', titleEs: 'Dashboard y Reportes', titleEn: 'Dashboard & Reports', descEs: 'Panel de metricas clave con cartera activa, pagos del dia, prestamos vencidos y comisiones. Reportes de cartera, estado de cuenta y pagos diarios.', descEn: 'Key metrics dashboard with active portfolio, daily payments, overdue loans and commissions. Portfolio, account statement and daily payment reports.' },
    ],
  },
  {
    slug: 'dental',
    name: 'eClinic',
    nameAccent: 'Dental',
    market: 'both',
    color: 'sky',
    icon: 'Smile',
    descEs: 'Sistema especializado de gestion para clinicas dentales con cumplimiento HIPAA. Odontograma interactivo, examen periodontal de 6 puntos, planes de tratamiento por diente y superficie, catalogo de procedimientos y verificacion de seguros en tiempo real.',
    descEn: 'HIPAA-compliant specialized dental practice management system. Interactive odontogram, 6-point periodontal exam, tooth and surface-level treatment plans, procedure catalog and real-time insurance eligibility verification.',
    cardDescEs: 'Gestion especializada para clinicas dentales con cumplimiento HIPAA. Pacientes, citas, odontograma, examen periodontal, planes de tratamiento y verificacion de seguros.',
    cardDescEn: 'HIPAA-compliant dental practice management. Patients, appointments, odontogram, periodontal exam, treatment plans and insurance verification.',
    tags: [
      { es: 'Pacientes', en: 'Patients' },
      { es: 'Citas', en: 'Appointments' },
      { es: 'Odontograma', en: 'Odontogram' },
    ],
    ctaEs: 'Moderniza tu clinica dental con eClinic Dental',
    ctaEn: 'Modernize your dental practice with eClinic Dental',
    ctaSubEs: 'Solicita una demostracion y descubre como eClinic Dental puede transformar la gestion de tu clinica dental.',
    ctaSubEn: 'Request a demo and discover how eClinic Dental can transform your dental practice management.',
    metaTitleEs: 'eClinic Dental - XoulTec | Sistema para Clinicas Dentales',
    metaTitleEn: 'eClinic Dental - XoulTec | Dental Practice Management',
    metaDescEs: 'eClinic Dental: Sistema especializado para clinicas dentales. Odontograma, periodoncia, planes de tratamiento y verificacion de seguros.',
    metaDescEn: 'eClinic Dental: Specialized dental practice management. Odontogram, periodontics, treatment plans and insurance verification.',
    features: [
      { icon: 'Smile', titleEs: 'Odontograma Interactivo', titleEn: 'Interactive Odontogram', descEs: 'Carta dental visual con numeracion FDI. Seguimiento de condiciones por diente y superficie (mesial, distal, bucal, lingual, oclusal). Visualizacion 3D de piezas dentales.', descEn: 'Visual dental chart with FDI numbering. Per-tooth and per-surface condition tracking (mesial, distal, buccal, lingual, occlusal). 3D tooth visualization.' },
      { icon: 'Activity', titleEs: 'Examen Periodontal', titleEn: 'Periodontal Exam', descEs: 'Sondeo de 6 puntos por diente con profundidad, recesion, sangrado, movilidad y furcacion. Graficos periodontales automaticos.', descEn: '6-point probing per tooth with depth, recession, bleeding, mobility and furcation. Automatic periodontal charts.' },
      { icon: 'ClipboardList', titleEs: 'Planes de Tratamiento', titleEn: 'Treatment Plans', descEs: 'Planes multi-fase con secuenciacion por prioridad. Detalle por diente y superficie con costos estimados y seguimiento de estado.', descEn: 'Multi-phase plans with priority sequencing. Tooth and surface-level detail with estimated costs and status tracking.' },
      { icon: 'FileText', titleEs: 'Catalogo de Procedimientos', titleEn: 'Procedure Catalog', descEs: 'Mas de 100 procedimientos organizados por categorias. Categorias: diagnostico, preventivo, restaurativo, endodoncia, periodoncia, prostodoncia y cirugia.', descEn: 'Over 100 procedures organized by category. Categories: diagnostic, preventive, restorative, endodontics, periodontics, prosthodontics and surgery.' },
      { icon: 'ShieldCheck', titleEs: 'Verificacion de Seguros', titleEn: 'Insurance Verification', descEs: 'Verificacion de elegibilidad en tiempo real via Stedi API. Validacion de plan, cobertura, beneficios y fechas de vigencia.', descEn: 'Real-time eligibility verification via Stedi API. Plan validation, coverage, benefits and effective dates.', highlight: true, badge: 'Real-time' },
      { icon: 'Calendar', titleEs: 'Citas y Agenda', titleEn: 'Appointments & Scheduling', descEs: 'Gestion de citas con duracion, tipo de consulta, recurrencia y recordatorios. Bloqueo automatico por elegibilidad de seguro.', descEn: 'Appointment management with duration, consultation type, recurrence and reminders. Automatic blocking based on insurance eligibility.' },
      { icon: 'Stethoscope', titleEs: 'Visitas y Notas Clinicas', titleEn: 'Visits & Clinical Notes', descEs: 'Documentacion SOAP completa con signos vitales, examenes, diagnosticos, prescripciones y ordenes de laboratorio.', descEn: 'Complete SOAP documentation with vitals, exams, diagnostics, prescriptions and lab orders.' },
      { icon: 'Users', titleEs: 'Gestion de Pacientes', titleEn: 'Patient Management', descEs: 'Historial medico y dental completo. Nivel de ansiedad, bruxismo, trastornos ATM, historial ortodontico e higiene oral.', descEn: 'Complete medical and dental history. Anxiety level, bruxism, TMJ disorders, orthodontic history and oral hygiene.' },
      { icon: 'ShieldCheck', titleEs: 'HIPAA Compliant', titleEn: 'HIPAA Compliant', descEs: 'Cumplimiento total con las regulaciones HIPAA. Proteccion de datos de salud protegidos (PHI), encriptacion, auditorias de acceso y politicas de privacidad integradas.', descEn: 'Full HIPAA compliance. Protected Health Information (PHI) safeguards, encryption, access audits and built-in privacy policies.', highlight: true, badge: 'Certified' },
    ],
  },
]

export function getProduct(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}
